name: C/C++ CI

on:
  push:
    branches: [ schwefel ]
  pull_request:
    branches: [ schwefel ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-20.04]

        fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: dependency (ubuntu)
      run: |
        sudo apt-get -q update 
        sudo apt-get -qy install python python3 \
            python3-numpy python3-pytest
    - name: dependency (custom)
      run: |
        export INSTALL_PREFIX=/usr
        sudo contrib/install.sh everything
    - name: clean
      run: |
          cd demo/Schwefel/
          make clean
    - name: make
      run: |
          cd demo/Schwefel/
          make
    - name: test
      run: |
          cd demo/Schwefel/
          make test
